version: "3.9"
services:
  goapp:
    build: .          # construye en base al Dockerfile encontrado en carpeta
    ports:
      - "3000:3000"
    links:
      - godb          # enlazar el contenedor goapp con el contenedor godb
  godb:
    image: mysql:8.0.29
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: goweb_crud
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
      # mongo     ->/data/db
      # mysql     ->/var/lib/mysql
      # postgres  ->/var/lib/postgresql/data

volumes:              # persistir datos de los contenedores DB, STORAGE
  db-data: